project_id = "qaxlpmxekcvbrcnqopbp"

[functions.search-prospects]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false
