project_id = "qaxlpmxekcvbrcnqopbp"

[functions.chatbot-webhook]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.firebase-config]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
