import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Loader2, CheckCircle, Send, Building2, HelpCircle } from "lucide-react";
import { motion } from "framer-motion";

const CATEGORY_LABELS: Record<string, string> = {
  modification_site: "Modification du site Internet",
  modification_carte_nfc: "Modification de la carte NFC",
  fiche_google: "Fiche Google My Business",
  reseaux_sociaux: "Réseaux sociaux",
  bug_technique: "Bug technique",
  question: "Question générale",
  autre: "Autre",
};

export default function SupportForm() {
  const { token } = useParams<{ token: string }>();
  const [client, setClient] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [form, setForm] = useState({
    category: "",
    subject: "",
    message: "",
    priority: "normale",
  });

  useEffect(() => {
    if (!token) return;
    const fetchClient = async () => {
      const { data, error } = await supabase
        .from("clients")
        .select("id, company_name, email, support_token")
        .eq("support_token", token)
        .single();
      if (error || !data) {
        setError("Lien invalide ou expiré");
      } else {
        setClient(data);
      }
      setLoading(false);
    };
    fetchClient();
  }, [token]);

  const handleSubmit = async () => {
    if (!form.category || !form.subject.trim() || !form.message.trim()) {
      toast.error("Veuillez remplir tous les champs obligatoires");
      return;
    }
    setSubmitting(true);
    try {
      // Insert ticket
      const { data: ticket, error: ticketError } = await supabase
        .from("support_tickets")
        .insert([{
          client_id: client.id,
          category: form.category,
          subject: form.subject,
          message: form.message,
          priority: form.priority,
          ticket_number: null, // auto-generated by trigger
        } as any])
        .select()
        .single();

      if (ticketError) throw ticketError;

      // Send notification via edge function
      try {
        await supabase.functions.invoke("support-notification", {
          body: {
            ticket_id: ticket.id,
            client_name: client.company_name,
            client_email: client.email,
            category: CATEGORY_LABELS[form.category] || form.category,
            subject: form.subject,
            message: form.message,
            ticket_number: ticket.ticket_number,
          },
        });
      } catch {
        // Don't fail the ticket creation if notification fails
        console.warn("Notification email failed");
      }

      setSubmitted(true);
    } catch (err) {
      toast.error("Erreur lors de l'envoi du support");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="max-w-md w-full">
          <CardContent className="flex flex-col items-center py-12">
            <HelpCircle className="w-12 h-12 text-muted-foreground/30 mb-4" />
            <h2 className="text-lg font-semibold mb-2">Lien invalide</h2>
            <p className="text-muted-foreground text-sm text-center">{error}</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (submitted) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}>
          <Card className="max-w-md w-full">
            <CardContent className="flex flex-col items-center py-12">
              <div className="w-16 h-16 rounded-full bg-success/10 flex items-center justify-center mb-4">
                <CheckCircle className="w-8 h-8 text-success" />
              </div>
              <h2 className="text-lg font-semibold mb-2">Demande envoyée !</h2>
              <p className="text-muted-foreground text-sm text-center">
                Votre demande de support a bien été enregistrée. Notre équipe reviendra vers vous dans les plus brefs délais.
              </p>
              <p className="text-xs text-muted-foreground mt-4">
                Un email de confirmation vous a été envoyé.
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <motion.div className="w-full max-w-lg" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
        <div className="text-center mb-6">
          <div className="flex items-center justify-center gap-2 mb-2">
            <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
              <Building2 className="w-5 h-5 text-primary" />
            </div>
          </div>
          <h1 className="text-2xl font-bold tracking-tight">Support Client</h1>
          <p className="text-muted-foreground text-sm mt-1">
            {client.company_name} — Formulaire de demande de support
          </p>
        </div>

        <Card className="border-0 shadow-lg">
          <CardContent className="p-6 space-y-4">
            <div className="space-y-2">
              <Label>Catégorie *</Label>
              <Select value={form.category} onValueChange={(v) => setForm({ ...form, category: v })}>
                <SelectTrigger><SelectValue placeholder="Sélectionnez une catégorie" /></SelectTrigger>
                <SelectContent>
                  {Object.entries(CATEGORY_LABELS).map(([k, v]) => (
                    <SelectItem key={k} value={k}>{v}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Objet *</Label>
              <Input
                value={form.subject}
                onChange={(e) => setForm({ ...form, subject: e.target.value })}
                placeholder="Ex: Mise à jour des horaires sur le site"
                maxLength={200}
              />
            </div>

            <div className="space-y-2">
              <Label>Description détaillée *</Label>
              <Textarea
                value={form.message}
                onChange={(e) => setForm({ ...form, message: e.target.value })}
                placeholder="Décrivez votre demande en détail..."
                rows={5}
                maxLength={2000}
              />
              <p className="text-xs text-muted-foreground text-right">{form.message.length}/2000</p>
            </div>

            <div className="space-y-2">
              <Label>Priorité</Label>
              <Select value={form.priority} onValueChange={(v) => setForm({ ...form, priority: v })}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="normale">Normale</SelectItem>
                  <SelectItem value="urgente">Urgente</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Button className="w-full gap-2" onClick={handleSubmit} disabled={submitting}>
              {submitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
              Envoyer la demande
            </Button>
          </CardContent>
        </Card>

        <p className="text-xs text-muted-foreground text-center mt-4">
          Propulsé par Adamkom by JJP
        </p>
      </motion.div>
    </div>
  );
}
